# Generated by Django 4.2 on 2023-04-06 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTasks',
            fields=[
                ('tasks_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.tasks')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_task', to='tasks.tasks')),
            ],
            bases=('tasks.tasks',),
        ),
    ]
